### ISSUE TITLE
hyperparameters in excel formula

### ISSUE THREAD

**Issue by slu1992** [matthewgilbert/blp#15]
it is quite common to use fill and days to get the bbg data if it is n/a or not a trading day (example shown below). 

=BDH(ticker, field, start_date, end_date, "Currency","USD","fill=p","days=a")

Not sure if there is a similar thing that I can do using this wrapper? I have tried "overrides" and "options" - they all failed unfortunately.

Thanks in advance!

**Comment by matthewgilbert** [comment]
If this is possible in the underlying `blpapi` then it should be possible via this wrapper however I'm unsure if the Excel features you are discussing are also possible in blpapi. Best to check this with Bloomberg help

**Comment by slu1992** [comment]
Thanks for your time response!

Yes, these parameters works in blpapi as another wrapper xbbg has it (though I didn't go through the underlying library). xbbg simply accepts the parameters like "Per=Y, Fill=P" in its blp and bdh functions. However, the return format of xbbg is obviously not as good as yours, so I wonder would be any way I could apply these parameters for pulling the data? Thanks again!

**Comment by matthewgilbert** [comment]
If that's the case it's likely xbbg is doing some translation to the options format the underlying blpapi expects (which is different than Excel). Your best bet would be to look through how that translation is handled and map to your call accordingly prior to calling blp.

**Comment by slu1992** [comment]
ah, thanks so much!!
