### ISSUE TITLE
Add BQL and EQS Query Examples to blp Quickstart Guide

### ISSUE THREAD

**Issue by pedroteles17** [matthewgilbert/blp#31]
Hello, @matthewgilbert!

Recently, I integrated BQL and EQS query support into `blp`. Would you be open to a pull request to update the Quickstart guide with examples demonstrating these endpoints?

Thank you!

**Comment by matthewgilbert** [comment]
Yes that would be great!

**Comment by pedroteles17** [comment]
@matthewgilbert, thanks for merging the PR!

Quick note: the `README.md` needs an updated quickstart link. I can deploy and update it via a new PR, or you can do it. Let me know your preference! Thanks!

**Comment by matthewgilbert** [comment]
@pedroteles17 I think the deployment actually broke the docs, see https://github.com/matthewgilbert/blp/issues/34

**Comment by matthewgilbert** [comment]
Closed by https://github.com/matthewgilbert/blp/pull/35
