### ISSUE TITLE
How do I get B-PIPE to work ?

### ISSUE THREAD

**Issue by rshah2019** [matthewgilbert/blp#5]
bquery = blp.BlpQuery(host='<host_name>', app='<app_name>').start()
    results = bquery.bdh(
        ["SPY US Equity", "TLT US Equity"],
        ["LAST_PRICE"],
        start_date="20211101",
        end_date="20211101",
    )

**I get an error: 
 'Data is not available for non-BPS Managed B-PIPE users. [nid:2938] ', 'subcategory': 'NOT_ENTITLED_FIELD'}}}}}**

My Bloomberg Rep tells me App should have permission to load LAST_PRICE from B-PIPE.  what I am doing wrong ?

**Comment by matthewgilbert** [comment]
I would try and troubleshoot makign raw connections via the `blpapi` library against `bpipe` first as I have limited experience interfacing with bpipe and there are several different authentication mechanisms.

**Comment by rshah2019** [comment]
got it, will do thank you
