### ISSUE TITLE
file handlers // connection leak

### ISSUE THREAD

**Issue by rshah2019** [matthewgilbert/blp#6]
It looks like my server crashes after few hours with file descriptor out of range error.   It seems like resource clean up may not be happening.   am I doing something wrong ? 

`  File "/usr/local/lib/python3.6/site-packages/waitress/wasyncore.py", line 245, in loop
    poll_fun(timeout, map)
  File "/usr/local/lib/python3.6/site-packages/waitress/wasyncore.py", line 172, in poll
    r, w, e = select.select(r, w, e, timeout)
ValueError: filedescriptor out of range in select()
`
```
from blp import blp
 sapiQuery = blp.BlpQuery(host='<name>', parser=blp.BlpParser(raise_security_errors=False)).start()
    sapiResults = sapiQuery.bdh(
        res['UnderlyingDefaultTicker'],
        ["PX_VOLUME_PRE_SESSION", "PX_LAST_PRE_SESSION"],
        start_date=today,
        end_date=today
    )
 sapiQuery.stop()
```

**Comment by matthewgilbert** [comment]
Not reproducible / clear if this issue is with this library or a dependency so closing.
