### ISSUE TITLE
Elements in bquery.bdh

### ISSUE THREAD

**Issue by gmurphy92** [matthewgilbert/blp#7]
Hey Matthew,

Thanks for the great work on pdblp and blp. I am porting over some code from pdblp to blp and noticed that for bquery.bdh the overrides are configured but not the elements (i.e. if you wanted to use [("calendarCodeOverride", "US")], not an FLDS override from the terminal). Think this corresponds to the setValues in the actual session request for pdblp vs the way the session is created in blp. 

Wondered if there a plans for that in blp or if theres a better way to pass the elements for a historical query in blp.

Thanks so much!

**Comment by matthewgilbert** [comment]
Do you have a small self contained example query in `pdblp` that you are having issues running with `blp`? I think you could just set that as an option in `bdh` no? I.e. `bdh(options={"calendarCodeOverride": "US"})`

**Comment by gmurphy92** [comment]
Ah i see thanks Matthew. I was still passing in a list of tuples from pdblp and didn't change the options to a dictionary.
